In [100]:
from tensorflow.keras.models import *
from keras.layers import *
from NN_real_extract import ModelExtractor
import numpy as np
import keras.initializers 

In [4]:



model = load_model('Models/mnist_convnet.h5')
# model.summary()

e = ModelExtractor('Models/resnet.h5')


In [3]:
dir(InputLayer)

['_TF_MODULE_IGNORED_PROPERTIES',
 '__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_add_trackable',
 '_add_trackable_child',
 '_add_variable_with_custom_getter',
 '_autographed_call',
 '_call_accepts_kwargs',
 '_call_arg_was_passed',
 '_call_fn_arg_defaults',
 '_call_fn_arg_positions',
 '_call_fn_args',
 '_call_full_argspec',
 '_cast_single_input',
 '_checkpoint_dependencies',
 '_clear_losses',
 '_compute_dtype',
 '_dedup_weights',
 '_deferred_dependencies',
 '_delete_tracking',
 '_deserialize_from_proto',
 '_dtype',
 '_eager_losses',
 '_flatten',
 '_flatten_layers',
 '_flatten_modules',
 '_functional_construction_call',
 

In [4]:
ip = model.layers[0]
print(ip.output_shape)
ext = e.InputLayer(ip)

[(None, 32, 32, 3)]


In [2]:
dir(Conv1D)

['_TF_MODULE_IGNORED_PROPERTIES',
 '__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_add_trackable',
 '_add_trackable_child',
 '_add_variable_with_custom_getter',
 '_autographed_call',
 '_call_accepts_kwargs',
 '_call_arg_was_passed',
 '_call_fn_arg_defaults',
 '_call_fn_arg_positions',
 '_call_fn_args',
 '_call_full_argspec',
 '_cast_single_input',
 '_checkpoint_dependencies',
 '_clear_losses',
 '_compute_causal_padding',
 '_compute_dtype',
 '_dedup_weights',
 '_deferred_dependencies',
 '_delete_tracking',
 '_deserialize_from_proto',
 '_dtype',
 '_eager_losses',
 '_flatten',
 '_flatten_layers',
 '_flatten_modules',
 '_func

In [123]:
input_shape = (4,10, 128)
inp = Input(input_shape[1:])
x = tf.random.normal(input_shape)
y = tf.keras.layers.Conv1D(32, 3, activation='relu')
model = Model(inputs=inp, outputs=y)

ValueError: Output tensors of a Functional model must be the output of a TensorFlow `Layer` (thus holding past layer metadata). Found: <keras.layers.convolutional.Conv1D object at 0x000002778CACFA48>

In [122]:
y.get_config()

AttributeError: 'KerasTensor' object has no attribute 'get_config'

In [95]:
model(x)

<tf.Tensor: shape=(4, 8, 32), dtype=float32, numpy=
array([[[0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 2.297403  , 0.        , ..., 0.        ,
         0.        , 1.2096386 ],
        [0.4959365 , 0.        , 0.        , ..., 3.078662  ,
         1.0114148 , 0.        ],
        ...,
        [2.9358494 , 0.        , 0.        , ..., 0.45769167,
         0.        , 1.4060116 ],
        [1.5462446 , 1.6690588 , 0.        , ..., 0.920365  ,
         1.3202851 , 0.30782485],
        [0.23403847, 0.        , 0.57916033, ..., 0.        ,
         0.        , 2.780488  ]],

       [[0.        , 1.1106331 , 1.1496084 , ..., 0.13142729,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 1.5362062 ,
         0.        , 0.        ],
        [0.85258746, 0.806553  , 0.        , ..., 0.        ,
         0.        , 0.        ],
        ...,
        [1.0935655 , 1.481106  , 0.        , ..., 0.    

In [104]:
type(model.layers[1].output_shape)

list

In [96]:
model.save('Models/test.h5')

AttributeError: The layer "conv1d_64" has never been called and thus has no defined output shape.

In [118]:
x = Conv1D(32, 3, kernel_initializer=keras.initializers.Ones() , bias_initializer=keras.initializers.Zeros())(tf.ones((10, 4, 1)))

In [119]:
print(x[0])
print(x.shape)

tf.Tensor(
[[3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
  3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
  3. 3. 3. 3. 3. 3. 3. 3.]], shape=(2, 32), dtype=float32)
(10, 2, 32)
